#!/bin/bash

#ENV DB_HOST 127.0.0.1
#ENV DB_ROOT_USER root
#ENV DB_ROOT_PASS <password>

#ENV DB_DMOJ_DB dmoj
#ENV DB_DMOJ_USER dmoj
#ENV DB_DMOJ_PASS <password>

#ENV POPULATE True



#Override local_settings
if [ -f /tmp/local_settings.py ]; then
    cp /tmp/local_settings.py /site/dmoj/local_settings.py
fi

envsubst < $DMOJ_PATH/dmoj/local_settings.py > $DMOJ_PATH//dmoj/local_settings.py
#Activate virtenv
. /dmojsite/bin/activate

# create DB and transfer

if ! mysql -u ${DB_ROOT_USER} -p ${DB_PASSWORD} -h ${DB_HOST} -e 'use ${DB_DMOJ_DB}'; then
  mysql -u ${DB_ROOT_USER} -p ${DB_PASSWORD} -h ${DB_HOST} -e "CREATE DATABASE ${DB_DMOJ_DB} DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;" &&\
  mysql -u ${DB_ROOT_USER} -p ${DB_PASSWORD} -h ${DB_HOST} -e "ALTER DATABASE ${DB_DMOJ_DB} CHARACTER SET utf8;" &&\
  mysql -u ${DB_ROOT_USER} -p ${DB_PASSWORD} -h ${DB_HOST} -e "GRANT ALL PRIVILEGES ON ${DB_DMOJ_DB}.* to '${DB_DMOJ_USER}'@'%' IDENTIFIED BY '${DB_DMOJ_PASS}';"
  python3 $DMOJ_PATH/manage.py migrate;
  if [ "${POPULATE}" = "True" ]; then /populate.sh; fi
fi

echo "Checking"
python3 $DMOJ_PATH/manage.py check || exit 1
echo "runbridged"
python3 $DMOJ_PATH/manage.py runbridged || exit 1

if [ "${DEBUG}" = "True" ]; then 
  echo "Testing mode"
  python $DMOJ_PATH/manage.py runserver ${DMOJ_HOST}:${DMOJ_PORT}
fi



