#!/bin/bash

#ENV DB_HOST 127.0.0.1
#ENV DB_ROOT_USER root
#ENV DB_ROOT_PASS <password>

#ENV DB_DMOJ_DB dmoj
#ENV DB_DMOJ_USER dmoj
#ENV DB_DMOJ_PASS <password>

#ENV POPULATE True



#Override local_settings
if [ -f /tmp/settings/local_settings.py ]; then
    cp /tmp/settings/local_settings.py /site/dmoj/local_settings.py
fi

envsubst < $DMOJ_PATH/dmoj/local_settings.py > $DMOJ_PATH/dmoj/local_settings.py
#Activate virtenv
. /dmojsite/bin/activate

# create DB and transfer
python3 $DMOJ_PATH/manage.py migrate
if [ "${POPULATE}" = "True" ]; then /populate.sh; fi

echo "Checking"
python3 $DMOJ_PATH/manage.py check || exit 1
echo "runbridged"
python3 $DMOJ_PATH/manage.py runbridged || exit 1

if [ "${DEBUG}" = "True" ]; then 
  echo "Testing mode"
  python $DMOJ_PATH/manage.py runserver ${DMOJ_HOST}:${DMOJ_PORT}
fi



