version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD='root_pass'
      - MYSQL_DATABASE='dmoj_db'
      - MYSQL_USER='dmoj'
      - MYSQL_PASSWORD='dmoj_password'
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
      
  dmoj_site:
    build: .
    restart: always
    ports:
      - 2000:2000
    environment:
      - DMOJ_PORT='2000'
      - DB_HOST='db'
      - DB_DMOJ_DB='dmoj_db'
      - DB_DMOJ_PASS='dmoj_password'
      - SECRET_KEY="This is not secret"
      - DEBUG='True' 
    volumes:
      - /home/jorpilo/codejam/Dmoj-site-docker/settings:/tmp/settings
    depends_on:
      - db
    entrypoint: /bin/bash
    

volumes:
  dmoj-db-vl:
