version: '0.1'

services:

  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: dmoj_db
      MYSQL_USER: dmoj
      MYSQL_PASSWORD: dmoj_password
    labels:
        character-set-server: "utf8mb4"
        collation-server: "utf8mb4_unicode_ci"
    volumes:
      - dmoj-db-vl:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  dmoj_site:
    build: .
    restart: always
    ports:
      - "2020:2020"
    environment:
      DMOJ_HOST: "0.0.0.0"
      DMOJ_PORT: "2020"
      DB_HOST: db
      DB_DMOJ_DB: dmoj_db
      DB_DMOJ_PASS: dmoj_password
      SECRET_KEY: "This is not secret"
      DEBUG: "True"
      ALLOWED_HOST: "'*'"
      POPULATE: "False"
    volumes:
      - ./settings:/tmp/settings
    depends_on:
      - db

volumes:
  dmoj-db-vl:
