version: '3.7'
# Please check parameters
# The following parameters must be the same
# db:MYSQL_DATABASE = dmoj_site:DB_DMOJ_DB
# db:MYSQL_USER = dmoj_site:DB_DMOJ_USER
# db:MYSQL_PASSWORD = dmoj_site:DB_DMOJ_USER


services:

  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: dmoj_db
      MYSQL_USER: dmoj
      MYSQL_PASSWORD: dmoj_password
    labels:
        character-set-server: "utf8mb4"
        collation-server: "utf8mb4_unicode_ci"
    volumes:
      - dmoj-db-vl:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
        - db
    restart: always
    ports:
      - "8080:8080"

  dmoj_site:
    build: .
    depends_on:
        - db
    restart: always
    ports:
      - "2020:80"
    environment:
      DMOJ_HOST: "0.0.0.0"
      DMOJ_PORT: "2020"
      DB_HOST: db
      DB_DMOJ_USER: dmoj
      DB_DMOJ_DB: dmoj_db
      DB_DMOJ_PASS: dmoj_password
      SECRET_KEY: "This is not secret"
      DEBUG: "False"
      ALLOWED_HOST: "'*'"
      POPULATE: "False"
    volumes:
      - ./settings:/tmp/settings


volumes:
  dmoj-db-vl:
